/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-08-19 02:58:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bottom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* 푸터 전체 컨테이너 */\r\n");
      out.write(".footer-container {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background-color: #000; \r\n");
      out.write("    color: #999; \r\n");
      out.write("    font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("    padding: 40px 0; \r\n");
      out.write("    font-size: 0.8rem; \r\n");
      out.write("    border-top: 1px solid #333; \r\n");
      out.write("    position: relative; /* sns-icons 위치 조정을 위해 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 헤더와 마찬가지로 실제 내용이 들어가는 1200px 영역 */\r\n");
      out.write(".footer-inner {\r\n");
      out.write("    max-width: 1200px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    text-align: center; \r\n");
      out.write("    line-height: 1.8; \r\n");
      out.write("    position: relative; /* sns-icons 위치 조정을 위해 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 회사 정보 (주소, 대표, 사업자번호 등) */\r\n");
      out.write(".footer-info p {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 정보들 사이의 구분선 */\r\n");
      out.write(".footer-info .separator {\r\n");
      out.write("    margin: 0 10px;\r\n");
      out.write("    color: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 저작권 정보 */\r\n");
      out.write(".footer-copyright {\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    font-size: 0.75rem; \r\n");
      out.write("    color: #777;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 푸터의 링크 */\r\n");
      out.write(".footer-links a {\r\n");
      out.write("    color: #999;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    margin: 0 10px;\r\n");
      out.write("    transition: color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-links a:hover {\r\n");
      out.write("    color: #eee; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* SNS 버튼 */\r\n");
      out.write(".sns-icons {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center; /* 중앙 정렬 */\r\n");
      out.write("    gap: 20px;\r\n");
      out.write("    margin-top: 20px; /* 저작권 위쪽 여백 */\r\n");
      out.write("    position: static; /* absolute 제거 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".sns-icon {\r\n");
      out.write("    width: 36px;\r\n");
      out.write("    height: 36px;\r\n");
      out.write("    filter: none; /* 검정색 아이콘 그대로 */\r\n");
      out.write("    transition: transform 0.3s;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sns-icon:hover {\r\n");
      out.write("    transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer-container\">\r\n");
      out.write("    <div class=\"footer-inner\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-links\">\r\n");
      out.write("            <a href=\"#\">이용약관</a> | \r\n");
      out.write("            <a href=\"#\">개인정보처리방침</a> | \r\n");
      out.write("            <a href=\"#\">고객센터</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-info\">\r\n");
      out.write("            <p>\r\n");
      out.write("                <strong>공간 시네마 (LX-CINEMA)</strong>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                <span>본사 홈페이지 : https://lxsiedu.or.kr</span>\r\n");
      out.write("                <span class=\"separator\">|</span>\r\n");
      out.write("                <span>대표 : 고영준</span>\r\n");
      out.write("                <span class=\"separator\">|</span>\r\n");
      out.write("                <span>사업자등록번호 : 123-45-67890</span>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                <span>대표전화 : 1588-1234</span>\r\n");
      out.write("                <span class=\"separator\">|</span>\r\n");
      out.write("                <span>오류 문의 : help@lxcinema.com</span>\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-copyright\">\r\n");
      out.write("            <p>&copy; LX-CINEMA Corp. All Rights Reserved.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- SNS 버튼 -->\r\n");
      out.write("        <div class=\"sns-icons\">\r\n");
      out.write("            <a href=\"https://www.instagram.com\" target=\"_blank\">\r\n");
      out.write("                <img src=\"asset/images/insta.png\" alt=\"인스타그램\" class=\"sns-icon\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"https://www.facebook.com\" target=\"_blank\">\r\n");
      out.write("                <img src=\"asset/images/facebook.png\" alt=\"페이스북\" class=\"sns-icon\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"https://www.youtube.com\" target=\"_blank\">\r\n");
      out.write("                <img src=\"asset/images/youtube.png\" alt=\"유튜브\" class=\"sns-icon\">\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
